### PR TITLE
Remove async module

### PR DESCRIPTION
**Pull request by shinnn**
It’s not needed any longer.

BrowserSync/UI#3

### CODE REVIEW

**Comment by shinnn** [comment]
Passed the test on both CI services.

**Comment by shakyShane** [comment]
:star:

**Comment by shinnn** [comment]
This gist helps you create cross-platform Node program.
https://gist.github.com/domenic/2790533

Especially, you shouldn't concatenate `__dirname` and the other path string. We should always use `path.*` method instead.

**Comment by shinnn** [comment]
By the way, I'm opposed to export external libs here.

https://github.com/shakyShane/browser-sync/blob/d203c04d08a82ce1c700c969caad520621d12fac/lib/utils.js#L346-L352

We are using Node, that is to say, we are using Common-JS. When should `require` the lib instead.

**Comment by shakyShane** [comment]
My goal was the removal of extra dependencies from the UI. Although it is technically a plugin to BrowserSync, it is inextricably linked. The idea of maintaining two sets of dependencies seemed more overhead that it's worth.

**Pull request merged**
